sudo: required
services:
- docker
env:
  global:
    # Ensure the downloaded SDK is first on the PATH
    - PATH=${HOME}/google-cloud-sdk/bin:$PATH
    # Ensure the install happens without prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: node_js
node_js:
- '6'
before_install:
- npm install
install:
- docker build -t cloudboost/dashboard-ui:2.0.$TRAVIS_BUILD_NUMBER .
- docker build -t cloudboost/dashboard-ui:latest .
after_success:
#Deploy.
#Docker Login
- docker login --username $DOCKERUSERNAME --password $DOCKERPASSWORD --email $DOCKEREMAIL
#Push docker images.
- docker push cloudboost/dashboard-ui:2.0.$TRAVIS_BUILD_NUMBER
- docker push cloudboost/dashboard-ui:latest
